#
# Makefile for the linux pmfs-filesystem routines.
#

obj-$(CONFIG_PMFS) += pmfs.o

pmfs-y := bbuild.o balloc.o dir.o file.o inode.o namei.o super.o symlink.o ioctl.o pmfs_stats.o journal.o xip.o wprotect.o
